AWSTemplateFormatVersion: 2010-09-09
Description: This template provisions a sample S3 bucket


# Defines parameters 
Parameters:

  SampleBucketName: 
    Type: String
    Default: ''

  TeamValue: 
    Type: String
    Default: ''
  
  OwnerValue:
    Type: String
    Default: 'tanea'



# Defines Resources 
Resources: 



# S3 Bucket
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref  SampleBucketName
      # Enable versioning of the bucket
      VersioningConfiguration:           
        Status: Enabled 

      Tags:
      - Key: team
        Value: !Ref TeamValue
      - Key: owner
        Value: !Ref OwnerValue

# Defines Outputs
Outputs:
   # SampleBucketName
   SampleBucketName:
     Description: S3 Bucket Name
     Value: !Ref SampleS3Bucket